### ISSUE TITLE
Use filesystem package for system path permissions in RPMs

### ISSUE THREAD

**Issue by amdprophet** [sensu/omnibus#5]
The current RPM packager makes some assumptions about ownership & permissions on system paths when adding the paths to the RPM spec file: https://github.com/chef/omnibus/blob/f60eb750b45751c27fc5f5d237798a620e98b2e8/lib/omnibus/packagers/rpm.rb#L329-L337

In CentOS 5 the permissions on `/usr/bin` are set to `755` but in CentOS 6+ they have changed to `555`.

We should update the RPM packager to determine the correct permissions for each system directory by inspecting the RPM spec file of the installed `filesystem` package or via some other means.

**Comment by annaplotkin** [comment]
Per discussion in ticket document, closing this issue. Not currently affecting our builds.
